### PR TITLE
fix: add plugin name for compatible with @vitejs/plugin-react

### LINKED ISSUE #38: Compatible with `@vitejs/plugin-react`
As `@vitejs/plugin-react-refresh` has been transformed to `@vitejs/plugin-react`, does the logic for finding `react-refresh`  in `vite-plugin-mdx` need to make the corresponding compatibility changes?

https://github.com/brillout/vite-plugin-mdx/blob/9220cb218277bace06007bc80826edca9b78cda9/src/index.ts#L41

[@vitejs/plugin-react `vite:react-babel`](https://github.com/vitejs/vite/blob/13c381368caf8302a0c5b7cec07dfc0eb344bede/packages/plugin-react/src/index.ts#L71)

### PR DESCRIPTION
**Pull request by Codpoe**
Fixes #38

### CODE REVIEW

**Comment by joshwooding** [comment]
@brillout Is there anything else needed for this?

**Comment by brillout** [comment]
> @brillout Is there anything else needed for this?

> We can still check after `@vitejs/plugin-react`'s name, in case there are some internal refactors.

**Comment by brillout** [comment]
Yes, but more precisely `p.name === 'react-refresh' || p.name === 'vite:react-babel || p.name === 'vite-plugin-react'`. We use `p.name === 'vite-plugin-react'` (or whatever the name of the plugin is) since we cannot assume what `vite-plugin-react` will eventually do.

File: src/index.ts [hunk 1]
```diff
@@ -35,10 +35,15 @@ function createPlugin(
...
+    enforce: 'pre',
     mdxOptions: globalMdxOptions,
     configResolved({ root, plugins }) {
-      const reactRefresh = plugins.find((p) => p.name === 'react-refresh')
+      // @vitejs/plugin-react-refresh has been upgraded to @vitejs/plugin-react,
+      // and the name of the plugin performing `transform` has been changed from 'react-refresh' to 'vite:react-babel',
+      // to be compatible, we need to look for both plugin name.
+      const reactRefresh = plugins.find(
+        (p) => p.name === 'react-refresh' || p.name === 'vite:react-babel'
+      )
```
Comment (joshwooding) [inline src/index.ts:46]:
```suggestion
      // We should also look for the other plugins names exported from @vitejs/plugin-react in case there are some internal refactors.
      const reactRefreshPlugins = plugins.filter(
        (p) => p.name === 'react-refresh' || p.name === 'vite:react-babel'
          || p.name === 'vite:react-refresh' || p.name === 'vite:react-jsx'
      );
      const reactRefresh = reactRefreshPlugins.find(p => p.transform);
```
This would also work

**Comment by brillout** [comment]
Released in `3.5.10`.
